### ISSUE TITLE
Support for non-Ruby based plugins

### ISSUE THREAD

**Issue by mrjcleaver** [ttscoff/Slogger#347]
I wrote something similar to slogger a few years ago.

I have an existing code base that I would consider bringing in. However, the plugins are all in Perl.

It would be nice to be able to call them.

**Comment by ttscoff** [comment]
You could write a plugin that conforms to the normal plugin methods but 
shells out to perl to run helper scripts that return the necessary 
strings to make an entry.

**Comment by mrjcleaver** [comment]
Hmm. Good point. Likewise to:
node.js e.g.
Elizabeth https://github.com/ttscoff/Slogger/issues/355 or
Python. 
E.g. https://github.com/durden/dayonetools

**Comment by lazyguru** [comment]
I would suggest closing this.  If someone really wants a plugin that uses an external langauge I think shelling out is what should be done and I don't think a PR should be accepted for it.  See my comment here: https://github.com/ttscoff/Slogger/issues/355#issuecomment-74102431
