### ISSUE TITLE
Have you considered using a backend ruby library?

### ISSUE THREAD

**Issue by mrjcleaver** [ttscoff/Slogger#351]
e.g. https://github.com/jyruzicka/rb-dayone

**Comment by ttscoff** [comment]
Why? Slogger predates all libraries I know of and has all the functions 
it needs to run without external dependencies...

**Comment by mrjcleaver** [comment]
Sure - I can quite understand you were ahead of the times.

Still, if someone else is documenting, testing and extending base functionality the less this team needs to do to make Slogger more capable than it already is.
