### ISSUE TITLE
Multimap gem problem

### ISSUE THREAD

**Issue by fmatic** [ttscoff/Slogger#360]
Hello,

Tested latest Slogger and bundle install gives error:

_"An error occurred while installing multimap (1.1.3), and Bundler cannot continue.
Make sure that `gem install multimap -v '1.1.3'` succeeds before bundling"._

Well next I run:
_gem install multimap -v '1.1.3'_ also tested with sudo and without -v 

And it fails with error:

_compiling nested_multimap_ext.c
nested_multimap_ext.c:13:47: warning: implicit declaration of function 'RHASH' is invalid in C99 [-Wimplicit-function-declaration]
                r = (i < argc) ? rb_hash_aref(h, argv[i]) : RHASH(h)->ifnone;
                                                            ^
nested_multimap_ext.c:13:57: error: member reference type 'int' is not a pointer
                r = (i < argc) ? rb_hash_aref(h, argv[i]) : RHASH(h)->ifnone;
                                                            ~~~~~~~~  ^
1 warning and 1 error generated.
make: *_\* [nested_multimap_ext.o] Error 1

make failed, exit code 2*

Any idea how to pass this?

**Comment by thiagodebastos** [comment]
:+1: Also getting this error

**Comment by base10** [comment]
Digging into multi map, it looks like there's an issue here: https://github.com/doxavore/multimap/commit/ee464be3d02c424970a29e39002ec7a8decc2721

**Comment by matk0** [comment]
@base10 Worked for me! Thanks a lot!

**Comment by deverman** [comment]
This helped now to solve the next error with 

An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.

**Comment by hmztsurukawa** [comment]
@base10 Worlks fine !  Thanks !!

**Comment by thejames** [comment]
@base10 Perfect solution! Thanks!

**Comment by bitboxer** [comment]
If I see correctly, only one plugin is using this outdated gem. Maybe @coopermj  will find time to update the olivetree plugin and remove the dependency?

**Comment by andrewgribben** [comment]
Following @base10 's instructions above and then restoring `gem 'multimap' # required for olivetree` to the Gemfile before running bundle install, solved this issue for me
