### ISSUE TITLE
OliveTree plugin not working?

### ISSUE THREAD

**Issue by jgclark** [ttscoff/Slogger#370]
I believe I've configured this plugin correctly, but when I run it, it never finds anything to log.
I've tried adding new notes in my OliveTree account, but still nothing shows up. Is there a way of debugging this further, please?

**Comment by coopermj** [comment]
Should be resolved now – if it's still not finding anything, go to line 388  and put in this code:
`puts res.body`

and then post what it spews. :)

**Comment by jgclark** [comment]
Many thanks, @coopermj it's now working for me (without line 388 change).
