### ISSUE TITLE
Cant install due to rmagick issue

### ISSUE THREAD

**Issue by Amparose** [ttscoff/Slogger#371]
When running `bundle install` I get the error "An error occurred while installing rmagick (2.13.2), and Bundler cannot continue."

`sudo gem install rmagick -v '2.13.2'` gives me some stuff with this looking relevant:

```
ERROR:  Error installing rmagick:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
checking for Ruby version >= 1.8.5... yes
checking for xcrun... yes
checking for Magick-config... no
Can't install RMagick 2.13.2. Can't find Magick-config in /usr/local/bin:/bin:/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
```

After finding this [solution on SO](http://stackoverflow.com/questions/19274293/error-installing-rmagick-error-failed-to-build-gem-native-extension) I ran `bundle install` again and receive another similar error for installing tilt (2.0.1). This leads me to believe that something isn't right as I don't think I should need to install all these bits separately in `brew` or something.

OSX Yosemite 10.10.3

Any ideas on how to get slogger to work?

**Comment by ttscoff** [comment]
#344
