### ISSUE TITLE
Support for day Day One Sync

### ISSUE THREAD

**Issue by arcterex** [ttscoff/Slogger#373]
Day One recently [announced a new sync option](http://dayoneapp.com/sync/), which is better than both iCloud and Dropbox (mostly), other than it's not supported by Slogger.  Can someone look at adding support for this?

**Comment by ttscoff** [comment]
There's still a local journal. Just point Slogger to that instead of 
your Dropbox journal.

**Comment by arcterex** [comment]
Duh.  Thanks!
