### ISSUE TITLE
InstapaperLogger not working: can't find RSS feed to configure

### ISSUE THREAD

**Issue by jgclark** [ttscoff/Slogger#377]
I've tried to configure this logger to run, having got other loggers running happily.

The header says:

```
  - Find the RSS feed for any folder at the bottom of the web interface page for that folder
Configuration:
...
  instapaper_feeds: [ 'http://www.instapaper.com/rss/106249/XXXXXXXXXXXXXX']
```

However, Instapaper has had a number of re-designs in the last year, and I can no longer see an RSS feed available. I have a free plan, but it's also not listed as a feature on the Premium plan.

Does anyone have this logger working still? If so, then it might be that the underlying RSS feature is still there, but the means to discover the URL for it has vanished.

This may or may not be related to issue #326.

**Comment by ttscoff** [comment]
View the source of the page and search for "rss". You should find a link 
like:

	<link rel="alternate" type="application/rss+xml" title="RSS" 
href="/rss/xxxxxx/xxxxxxxx" />

append the href portion of that url to 'http://www.instapaper.com' and 
see if that works.

**Comment by jgclark** [comment]
Great. That's done it -- albeit with https not http.  I've done my first Github update in order to update the plugin's instructions to reflect this. I hope I've done the right thing.

Many thanks.
