### ISSUE TITLE
UTC vs TimeZones

### ISSUE THREAD

**Issue by mrjcleaver** [ttscoff/Slogger#391]
Hi Brett,

I can't figure it out - does Slogger keep it's time always in UTC, or in localtime? Does it depend on what's in the slogger_config?

Got a bug somewhere... this would help!

Thanks, M.

**Comment by ttscoff** [comment]
It should resolve dates to system time based on time zone specifiers in any response data. I honestly haven't looked at the code for quite a while, so let me know there's something I can clarify further.

**Comment by mrjcleaver** [comment]
Thanks Brett. So slogger.rb and slogger_config appear to store in local time. Appreciated.
