### ISSUE TITLE
REQUEST - Trakt.tv plugin?

### ISSUE THREAD

**Issue by mcdent** [ttscoff/Slogger#400]
I noticed there is a trakt plugin which appears to be disabled?
Is there any chance this can be resurrected? There are a lot of services/apps now which report back to trakt.tv and allow you to keep a history of your viewing habits. It would be nice to have this in Day One if possible?
Thanks
Mike

**Comment by ttscoff** [comment]
Plugins in the "plugins_disabled" folder just need to be moved to the 
plugins folder (and vice versa to disable plugins). I can't vouch for 
the functionality of 3rd party contributions, but it's just disabled, 
not deprecated.

-Brett

**Comment by mcdent** [comment]
Thanks.
