### ISSUE TITLE
LastFM plugin failing

### ISSUE THREAD

**Issue by griffey** [ttscoff/Slogger#404]
Slogger itself is running fine with just the Twitter and Foursquare plugins, but I'd love to be able to include the LastFM plugin for my scrobbled songs. Currently, after installation and updating the slogger config, running Slogger just gets the timeout error ("Error performing action, retrying 1/3"). Does that three times, then fails. 

I've checked the log, nothing seems useful there, and have checked the config, which accurately reflects my username. Anyone having issues?

**Comment by ats** [comment]
The plugin stopped working when last.fm launched the new site several months ago; they killed the feed that slogger uses to read your activity, and have not yet indicated that it's coming back. It's unfortunate that the activity feed isn't usable, but the update also made scrobbling so unreliable for me that I decided to basically give up on the service, anyway.

cheers,
Alan

**Comment by griffey** [comment]
Ah. Well crud. Maybe noting that in the Readme would be good. :-) 

Thanks for letting me know.

**Comment by ttscoff** [comment]
Yeah, I'm kinda bummed with all the changes that have messed up all of 
my Last.fm integrations across the board. Not terribly useful anymore.

-Brett
