### ISSUE TITLE
undefined method `[]'

### ISSUE THREAD

**Issue by randomphrase** [ttscoff/Slogger#421]
Slogger hasn't run automatically for a few weeks now, so I pulled the latest code and ran it from the command line. I got an undefined method error:

```
$ ./slogger
/Users/alastair/Library/Slogger/slogger.rb:195:in `initialize': undefined method `[]' for false:FalseClass (NoMethodError)
    from /Users/alastair/Library/Slogger/slogger.rb:448:in `new'
    from /Users/alastair/Library/Slogger/slogger.rb:448:in `<top (required)>'
    from     /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from     /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from ./slogger:18:in `<main>'
```

Any help appreciated.

**Comment by ttscoff** [comment]
Not sure about this one. Are you running the latest version (2.1.14)?

-Brett

**Comment by randomphrase** [comment]
Hi, this is still happening. I haven't been able to run slogger for months now. Not sure exactly what I'm doing wrong. I've pulled the latest and also bundle updated to the latest dependencies. Unfortunately still getting this issue. Is there something I can do to help track this down? Looks like a pretty fundamental problem.

**Comment by larryhynes** [comment]
I'm willing to assume it's a pretty fundamental problem that is specific to your setup, mostly on the basis that nobody else has chimed in on this issue in over 6 months. Were I in your shoes, I would try to isolate the problem by a). backing up my entire slogger directory b). doing a clean install of slogger and c). trying some different ruby versions, using rvm or rbenv to pick and choose between them.

> I've pulled the latest and also bundle updated to the latest dependencies.

When you do this, are you running slogger with your existing config file? Does slogger fail with a completely fresh config?
